name: a2gen
description: Sample user data generator for Intersubjective Gravity Server
version: 0.2.0

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  faker: ^2.1.0
  graphql: ^5.1.3
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0
