name: a2gen
description: Sample user data generator for Intersubjective Gravity Hasura DB
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  yaml: ^3.1.0
  graphql: ^5.1.3
  faker: ^2.1.0
  collection: ^1.17.2
  args: ^2.4.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
